CREATE DATABASE SENAI_HROADS_TARDE;
GO

USE	SENAI_HROADS_TARDE;
GO

CREATE TABLE CLASSE (

	idClasse TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeClasse VARCHAR(20) NOT NULL UNIQUE
  
);
GO

CREATE TABLE PERSONAGEM (

	idPersonagem TINYINT PRIMARY KEY IDENTITY(1,1),
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse), 
	nomePersonagem VARCHAR(20) NOT NULL UNIQUE,
    ptsVida SMALLINT NOT NULL,
	ptsMana SMALLINT NOT NULL,
	dataCriacao DATE NOT NULL,
	dataAtualizacao DATE NOT NULL
  
);
GO

CREATE TABLE TIPOHABILIDADE (
	idTipoHabilidade TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeTipoHabilidade VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE HABILIDADE (
	idHabilidade SMALLINT PRIMARY KEY IDENTITY(1,1),
	idTipoHabilidade TINYINT FOREIGN KEY REFERENCES TIPOHABILIDADE(idTipoHabilidade), 
	nomeHabilidade VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE CLASSEHABILIDADE (
	idClasseHabilidade SMALLINT PRIMARY KEY IDENTITY(1,1),
	idHabilidade SMALLINT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade), 
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse)
);
GO

CREATE TABLE TIPOUSUARIO (

	idTipoUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
	titulo VARCHAR(100) NOT NULL

);
GO

CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY(1,1),
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	email VARCHAR(300) NOT NULL UNIQUE,
	senha VARCHAR(16) NOT NULL CONSTRAINT USUARIO_SENHA_CK CHECK (LEN(senha) >= 8)
);
GO
